blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.zerobridge.xyz/
    about: ZeroBridge documentation
  - name: Support
    url: https://discord.gg/nomadxyz
    about: This issue tracker is only for bugs and feature requests. Support is available on Discord!
